### ISSUE TITLE
Create a README.md

### ISSUE THREAD

**Issue by alsmola** [SWBUCB/LROSecurity#1]
When you visit this project on github, it would be great if it had a README.md to render. Not sure, but seems like a combo of `0-Introduction and TOC.md` and `Cover.md` would work. Maybe whatever publish step you use for the PDF could do this?

**Comment by SWBUCB** [comment]
Agreed - question though: lots of readers won't be familiar with Github terminology. Would it be appropriate to bracket README in the file name and keep the "intro and TOC" name, so they know what they're looking at? Concern is readers won't know README is an intro in most instances.

Or, we could just dupe the content and have a readme with the content *in addition* the original files?

**Comment by alsmola** [comment]
Yeah I was suggesting duplicates (maybe hidden in a `.github` directory, see https://help.github.com/articles/about-readmes/) that were automatically generated. Another approach could just a be a simple README.md that points to intro and TOC.

**Comment by guntbert** [comment]
@alsmola using the `.github` directory is an excellent idea.
I don't like to duplicate anything so I'd advocate for your second suggestion (creating links).
